# These are supported funding model platforms
custom: [ 'https://www.linkedin.com/in/eduardo-p-gomez-b55763188', 'https://www.paypal.com/donate/?cmd=_donations&business=AC44X3D94K8NL&item_name=develop+more+incredible+tools&currency_code=BRL' ]
